import type {
  ActivityItem,
  DashboardStats,
  RfpRecord,
  TeamMember,
} from "@/types/rfp";

export const mockRfps: RfpRecord[] = [
  {
    id: "rfp-001",
    title: "Waterwise Public Outreach Campaign",
    client: "City of Bend",
    source: "justwin",
    externalId: "JW-2026-1842",
    sector: "Public Sector",
    location: "Bend, OR",
    dueDate: "2026-06-20",
    receivedDate: "2026-06-05",
    stage: "go_no_go",
    status: "pending_approval",
    priority: "high",
    fitScore: 92,
    worthScore: 88,
    goNoGo: "go",
    assignedTo: "Rachel",
    estimatedValue: 185000,
    pageLimit: 25,
    lastActivity: "2026-06-11T14:30:00",
    lastActivityNote: "Go/No-Go analysis complete — awaiting Sonja approval",
    contractRole: "prime",
  },
  {
    id: "rfp-002",
    title: "Digital Communications Services",
    client: "Deschutes County",
    source: "justwin",
    externalId: "JW-2026-1839",
    sector: "Public Sector",
    location: "Bend, OR",
    dueDate: "2026-06-25",
    receivedDate: "2026-06-04",
    stage: "sections_4_5",
    status: "in_progress",
    priority: "high",
    fitScore: 95,
    worthScore: 90,
    goNoGo: "go",
    assignedTo: "Morgan",
    estimatedValue: 240000,
    pageLimit: 40,
    lastActivity: "2026-06-11T09:15:00",
    lastActivityNote: "Section 4 approach draft in review",
    contractRole: "prime",
  },
  {
    id: "rfp-003",
    title: "Brand Refresh & Identity System",
    client: "University of Idaho ATP",
    source: "justwin",
    externalId: "JW-2026-1831",
    sector: "Higher Education",
    location: "Moscow, ID",
    dueDate: "2026-07-02",
    receivedDate: "2026-06-03",
    stage: "compliance",
    status: "active",
    priority: "medium",
    fitScore: 87,
    worthScore: 82,
    goNoGo: "go",
    assignedTo: "Alex",
    estimatedValue: 120000,
    pageLimit: 30,
    lastActivity: "2026-06-10T16:45:00",
    lastActivityNote: "Compliance map generated — 18 required sections",
    contractRole: "prime",
  },
  {
    id: "rfp-004",
    title: "Workforce Outreach & Digital Campaign",
    client: "Oregon Employment Department",
    source: "justwin",
    externalId: "JW-2026-1825",
    sector: "Public Sector",
    location: "Salem, OR",
    dueDate: "2026-06-18",
    receivedDate: "2026-06-02",
    stage: "pricing",
    status: "in_progress",
    priority: "critical",
    fitScore: 91,
    worthScore: 85,
    goNoGo: "go",
    assignedTo: "Jordan",
    estimatedValue: 310000,
    pageLimit: 35,
    lastActivity: "2026-06-11T11:00:00",
    lastActivityNote: "Pricing tiers drafted from Pricing Guide",
    contractRole: "prime",
  },
  {
    id: "rfp-005",
    title: "Community Engagement Strategy",
    client: "City of Medford",
    source: "justwin",
    externalId: "JW-2026-1818",
    sector: "Public Sector",
    location: "Medford, OR",
    dueDate: "2026-06-15",
    receivedDate: "2026-06-01",
    stage: "review",
    status: "review",
    priority: "critical",
    fitScore: 89,
    worthScore: 86,
    goNoGo: "go",
    assignedTo: "Sam",
    estimatedValue: 95000,
    pageLimit: 20,
    lastActivity: "2026-06-11T08:30:00",
    lastActivityNote: "Pre-submission voice & compliance review in progress",
    contractRole: "prime",
  },
  {
    id: "rfp-006",
    title: "Patient Education Portal & Campaign",
    client: "Pacific Northwest Health Alliance",
    source: "justwin",
    externalId: "JW-2026-1810",
    sector: "Healthcare",
    location: "Portland, OR",
    dueDate: "2026-06-22",
    receivedDate: "2026-05-30",
    stage: "go_no_go",
    status: "pending_approval",
    priority: "medium",
    fitScore: 62,
    worthScore: 55,
    goNoGo: "review",
    assignedTo: "Rachel",
    estimatedValue: 450000,
    pageLimit: 50,
    lastActivity: "2026-06-09T13:20:00",
    lastActivityNote: "Fit score low — capability outside core marketing flagged",
    contractRole: "subconsultant",
  },
  {
    id: "rfp-007",
    title: "State IT Services Website Redesign",
    client: "State of Oregon",
    source: "justwin",
    externalId: "JW-2026-1802",
    sector: "Public Sector",
    location: "Salem, OR",
    dueDate: "2026-06-12",
    receivedDate: "2026-05-28",
    stage: "intake",
    status: "new",
    priority: "high",
    fitScore: null,
    worthScore: null,
    goNoGo: null,
    assignedTo: null,
    estimatedValue: null,
    pageLimit: 45,
    lastActivity: "2026-06-11T07:00:00",
    lastActivityNote: "New intake from JustWin — PDF pending download",
    contractRole: "prime",
  },
  {
    id: "rfp-009",
    title: "Tourism Marketing & Brand Campaign",
    client: "Hood River County",
    source: "justwin",
    externalId: "JW-2026-1795",
    sector: "Public Sector",
    location: "Hood River, OR",
    dueDate: "2026-06-28",
    receivedDate: "2026-05-27",
    stage: "sections_1_3",
    status: "in_progress",
    priority: "medium",
    fitScore: 88,
    worthScore: 84,
    goNoGo: "go",
    assignedTo: "Morgan",
    estimatedValue: 165000,
    pageLimit: 28,
    lastActivity: "2026-06-10T10:00:00",
    lastActivityNote: "Case studies auto-filled — Hampton Lumber, City of Bend",
    contractRole: "prime",
  },
  {
    id: "rfp-010",
    title: "Recovery Network Awareness Campaign",
    client: "Recovery Network of Oregon",
    source: "justwin",
    externalId: "JW-2026-1788",
    sector: "Nonprofit",
    location: "Portland, OR",
    dueDate: "2026-07-08",
    receivedDate: "2026-05-25",
    stage: "compliance",
    status: "active",
    priority: "low",
    fitScore: 93,
    worthScore: 91,
    goNoGo: "go",
    assignedTo: "Alex",
    estimatedValue: 78000,
    pageLimit: 22,
    lastActivity: "2026-06-08T15:30:00",
    lastActivityNote: "Structural map complete — 12-day timeline on track",
    contractRole: "prime",
  },
];

export const mockActivity: ActivityItem[] = [
  {
    id: "act-1",
    rfpId: "rfp-001",
    rfpTitle: "City of Bend — Waterwise",
    action: "Go/No-Go analysis completed",
    actor: "Claude",
    timestamp: "2026-06-11T14:30:00",
  },
  {
    id: "act-2",
    rfpId: "rfp-005",
    rfpTitle: "City of Medford — Community Engagement",
    action: "Entered pre-submission review",
    actor: "Sam",
    timestamp: "2026-06-11T08:30:00",
  },
  {
    id: "act-3",
    rfpId: "rfp-004",
    rfpTitle: "Oregon Employment Dept",
    action: "Pricing assistant generated 3 tiers",
    actor: "Claude",
    timestamp: "2026-06-11T11:00:00",
  },
  {
    id: "act-4",
    rfpId: "rfp-007",
    rfpTitle: "State of Oregon — IT Services",
    action: "New RFP detected via JustWin",
    actor: "System",
    timestamp: "2026-06-11T07:00:00",
  },
  {
    id: "act-5",
    rfpId: "rfp-002",
    rfpTitle: "Deschutes County",
    action: "Section 4 draft updated",
    actor: "Morgan",
    timestamp: "2026-06-11T09:15:00",
  },
];

export const mockTeam: TeamMember[] = [
  { name: "Morgan", role: "RFP Writer", activeCount: 2, capacity: 3 },
  { name: "Alex", role: "RFP Writer", activeCount: 2, capacity: 3 },
  { name: "Jordan", role: "RFP Writer", activeCount: 1, capacity: 3 },
  { name: "Sam", role: "RFP Writer", activeCount: 1, capacity: 3 },
  { name: "Rachel", role: "Triage Lead", activeCount: 2, capacity: 4 },
];

export function computeStats(rfps: RfpRecord[]): DashboardStats {
  const now = new Date();
  const weekFromNow = new Date(now);
  weekFromNow.setDate(weekFromNow.getDate() + 7);

  const active = rfps.filter(
    (r) => !["won", "lost", "passed", "submitted"].includes(r.status)
  );

  const scored = active.filter((r) => r.fitScore !== null);

  return {
    activeRfps: active.length,
    pendingGoNoGo: rfps.filter(
      (r) => r.stage === "go_no_go" && r.status === "pending_approval"
    ).length,
    inProgress: rfps.filter(
      (r) => ["in_progress", "active", "review"].includes(r.status)
    ).length,
    dueThisWeek: active.filter((r) => {
      const due = new Date(r.dueDate);
      return due >= now && due <= weekFromNow;
    }).length,
    submittedThisMonth: 3,
    winRate: 10,
    pipelineValue: active.reduce((sum, r) => sum + (r.estimatedValue ?? 0), 0),
    avgFitScore:
      scored.length > 0
        ? Math.round(
            scored.reduce((s, r) => s + (r.fitScore ?? 0), 0) / scored.length
          )
        : 0,
  };
}
